(async function(){
'use strict';
const R=AnimalRules,app=document.getElementById('app');
let data,screen='overview',selected=null,filter='all',speciesFilter='',query='',locationFilter='',breedFilter='',showArchived=false,eventFilter='',recordTypeFilter='',dateFilter='',draftTimer,saveBusy=false,activePhoto='',pendingPreview=null,formBack='animals';
const uuid=()=>crypto.randomUUID(),today=()=>{const d=new Date();return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10);};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=(name,args={})=>FarmerPlus.call(name,args);
const labelType=id=>[...R.TYPES,...(data?.state.types||[])].find(t=>t.id===id)?.name||id;
const locName=id=>data.locations.find(l=>l.id===id)?.data.name||'Location not recorded';
const farmName=id=>data.farms.find(l=>l.id===id)?.data.name||'Farm';
const currentFarm=()=>data.farmId;
const ctx=()=>({farms:Object.fromEntries(data.farms.map(f=>[f.id,f.data])),locations:Object.fromEntries(data.locations.map(l=>[l.id,l.data.farmId]))});
const currentProfiles=()=>data.state.profiles.filter(p=>!p.deleted&&p.farmId===currentFarm());
const subject=id=>data.state.profiles.find(p=>p.id===id);
const title=p=>p?.name||p?.tag||'Animal';
function icon(type){const paths={cattle:'M8 12 3 5l8 3m13 4 5-7-8 3M10 9c-3 4-3 9-1 13l3 4h8l3-4c2-4 2-9-1-13ZM12 20h8v5h-8ZM12 14h.1M20 14h.1',chicken:'M11 13c-4 1-6 5-4 9 2 3 9 4 13 0l3-5h-5V9c0-4-6-5-7-1Zm7-3 6 2-6 2M12 6l-1-3 3 2 2-3 1 4M11 25v4m7-4v4',pigs:'M5 13 4 7l7 3c4-2 8-1 11 2l5-3v8c0 6-5 9-11 9S5 22 5 17ZM10 18h12v6H10ZM13 21h.1M19 21h.1M10 14h.1M22 14h.1',goats:'M10 10C5 8 5 3 9 2m13 8c5-2 5-7 1-8M10 11 4 9l4 6m14-4 6-2-4 6M10 11h12l-2 12-4 5-4-5ZM12 16h.1M20 16h.1M14 28l2 3 2-3',sheep:'M9 10c-6-3-8 6-3 8-2 5 3 9 7 6 4 5 11 1 9-3 7 0 9-10 2-12 0-6-7-7-9-2-3-4-8-1-6 3ZM11 12h10l-2 11h-6ZM14 16h.1M18 16h.1'};return `<svg viewBox="0 0 32 32" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[type]||paths.cattle}"/></svg>`;}
function symbol(type){return `<span class="species-icon">${icon(type)}</span>`;}
function notice(message){const n=document.getElementById('notice');n.textContent=message;n.style.display='block';setTimeout(()=>n.style.display='none',4000);}
function error(message){let e=document.getElementById('error');if(!e){e=document.createElement('div');e.id='error';e.className='error';e.setAttribute('role','alert');app.querySelector('.content')?.prepend(e);}e.textContent=message;e.scrollIntoView({block:'nearest'});}
function theme(t){if(!t)return;for(const [k,v] of Object.entries(t.colors||{}))document.documentElement.style.setProperty('--'+k,v);document.documentElement.style.colorScheme=t.dark?'dark':'light';document.documentElement.style.fontSize=(16*(t.textScale||1))+'px';}
function status(){return `<div class="status ${data.conflict?'error':''}" role="status">${esc(data.status||'Saved on this device')}${data.queue?.length?` · ${data.queue.length} pending`:''}</div>`;}
function button(text,action,extra='',cls=''){return `<button type="button" class="${cls}" data-action="${action}" ${extra}>${text}</button>`;}
function header(){return `<div class="topline"><div><span class="farm-label">Your farm</span><select id="farm" class="farm-select" aria-label="Selected farm">${data.farms.map(f=>`<option value="${f.id}" ${f.id===currentFarm()?'selected':''}>${esc(f.data.name)}</option>`).join('')}</select></div><div class="header-actions">${button('↻','sync','aria-label="Sync animal records"','quiet')}${button('•••','options','aria-label="Animal options"','quiet')}</div></div>`;}
function nav(){return `<nav class="bottom-nav" aria-label="My Animals">${[['overview','Overview','⌂'],['animals','Animals',''],['records','Records','≡']].map(([id,label,glyph])=>`<button data-action="nav" data-screen="${id}" ${screen===id?'aria-current="page"':''}>${glyph?`<span aria-hidden="true" style="font-size:23px">${glyph}</span>`:icon('cattle')}<span>${label}</span></button>`).join('')}</nav>`;}
function setScreen(s){screen=s;pendingPreview=null;render();document.querySelector('h1')?.focus();window.scrollTo(0,0);}
function activeList(){return currentProfiles().filter(p=>showArchived?!p.active:p.active).filter(p=>filter==='all'||p.kind===(filter==='groups'?'group':'individual')).filter(p=>!speciesFilter||p.species===speciesFilter).filter(p=>!locationFilter||(p.locationId||'unknown')===locationFilter).filter(p=>!breedFilter||(p.breed||'').toLowerCase().includes(breedFilter.toLowerCase())).filter(p=>[p.name,p.tag,p.breed].some(v=>(v||'').toLowerCase().includes(query.toLowerCase())));}
function animalRow(p){return `<button class="animal-row" data-action="detail" data-id="${p.id}">${symbol(p.species)}<span class="body"><strong>${esc(title(p))}</strong><small>${esc(labelType(p.species))}${p.breed?' · '+esc(p.breed):''} · ${p.kind==='group'?p.count+' animals':esc(p.tag||'Individual')}</small><span class="location">${esc(locName(p.locationId))}${!p.active?' · Inactive':''}</span></span><span class="chevron" aria-hidden="true">›</span></button>`;}
function eventText(e){const p=subject(e.subjectId),name=title(p),n=e.quantity;switch(e.type){case 'opening':return p?.kind==='group'?`${n} ${labelType(p.species).toLowerCase()} recorded`:`${name} added`;case 'addition':return `${n} added · ${e.reason}`;case 'departure':return `${p?.kind==='group'?n+' animals':name} · ${e.reason}`;case 'move':return `${p?.kind==='group'?n+' animals':name} moved to ${locName(e.locationId)}`;case 'identify':return `One animal identified from ${name}`;case 'count':return `Count corrected to ${n}`;case 'weight':return `Weight recorded · ${e.weight} ${e.unit}`;case 'care':return 'Care or treatment recorded';case 'observation':return 'Health observation recorded';case 'return':return `${name} returned`;default:return 'Note recorded';}}
function eventsForFarm(){return data.state.events.filter(e=>{const p=subject(e.subjectId),d=subject(e.destinationId);return p?.farmId===currentFarm()||d?.farmId===currentFarm()||e.farmId===currentFarm();}).sort((a,b)=>b.occurredOn.localeCompare(a.occurredOn)||b.order-a.order);}
function eventRow(e){return `<button class="event" data-action="event-detail" data-id="${e.id}">${symbol(subject(e.subjectId)?.species)}<span class="body"><strong>${esc(eventText(e))}</strong><small>${esc(title(subject(e.subjectId)))} · ${esc(e.occurredOn)}${e.void?' · Removed':e.revisions?.length?' · Corrected':''}</small></span><span aria-hidden="true">›</span></button>`;}
function empty(message,description,action,label){return `<div class="card empty">${symbol('cattle')}<h2>${esc(message)}</h2><p class="muted">${esc(description)}</p>${action?button(label,action,'','primary'):''}</div>`;}
function overview(){const ps=currentProfiles().filter(p=>p.active),groups=ps.filter(p=>p.kind==='group'),individuals=ps.filter(p=>p.kind==='individual'),total=ps.reduce((s,p)=>s+p.count,0);return `<h1 tabindex="-1">My Animals</h1><p class="muted">A clear picture of the animals on your farm.</p>${!ps.length?empty('Start with one animal or a whole group','Save the details you know. You can add more later.','add-choice','Add animals'):`<section class="card hero"><div class="count-line"><strong class="total">${total.toLocaleString()}</strong><span>animals on this farm</span></div><p class="muted">${groups.reduce((s,p)=>s+p.count,0)} in ${groups.length} groups · ${individuals.length} individual${individuals.length===1?'':'s'}</p><div class="species-grid">${[...R.TYPES,...data.state.types.filter(t=>ps.some(p=>p.species===t.id))].map(t=>`<button data-action="species" data-id="${t.id}">${icon(t.id)}<b>${ps.filter(p=>p.species===t.id).reduce((s,p)=>s+p.count,0)}</b><span>${esc(t.name)}</span></button>`).join('')}</div></section><div class="actions">${button('+ Record something','record-choice','','primary')}${button('Add animals','add-choice')}</div>`}${data.draft?`<div class="card"><h3>Your saved draft</h3><p>Continue where you left off.</p><div class="actions">${button('Continue draft','resume-draft')}${button('Discard draft','discard-draft','','quiet')}</div></div>`:''}<div class="section-title"><h2>Recent records</h2>${button('View all','nav','data-screen="records"','quiet')}</div><section class="card">${eventsForFarm().slice(0,3).map(eventRow).join('')||'<p class="muted">Your animal records will appear here.</p>'}</section>`;}
function animals(){return `<h1 tabindex="-1">Animals</h1><p class="muted">Find an individual animal or a group.</p><input class="search" id="search" type="search" placeholder="Search names, tags or breeds" aria-label="Search animals" value="${esc(query)}"><div class="chiprow">${[['all','All'],['individuals','Individuals'],['groups','Groups']].map(([v,l])=>button(l,'filter',`data-id="${v}" aria-pressed="${filter===v}"`)).join('')}${button('Filters','filters','','quiet')}</div><div id="animal-results" class="list animals">${animalResults()}</div><div class="actions">${button('+ Add animals','add-choice','','primary')}</div>`;}
function animalResults(){return activeList().map(animalRow).join('')||empty('No animals found','Try another search or clear your filters.','clear-filters','Clear filters');}
function detail(){const p=subject(selected);if(!p)return empty('Animal unavailable','Return to your animals.','nav','Animals');return `${button('‹ Animals','nav','data-screen="animals"','quiet')}<div class="card"><div class="row">${symbol(p.species)}<span class="badge">${p.kind==='group'?'Group':'Individual'}</span></div><h1 tabindex="-1">${esc(title(p))}</h1><p class="muted">${esc(labelType(p.species))}${p.breed?' · '+esc(p.breed):''}${p.tag?' · Tag '+esc(p.tag):''}</p><div class="count-line"><strong class="total" style="font-size:40px">${p.count}</strong><span>${p.kind==='group'?'animals':'animal'}${!p.active?' · Inactive':''}</span></div><p>Where they are kept<br><strong>${esc(locName(p.locationId))}</strong></p>${p.photo?'<img id="detail-photo" class="photo-preview" alt="Animal photo">':''}</div><div class="actions">${button('+ Record something','record-choice',`data-id="${p.id}"`,'primary')}${button('Edit details','edit',`data-id="${p.id}"`)}</div><dl class="summary-dl">${[['Sex',p.sex],['Birth date',p.birthDate],['Estimated age',p.estimatedAge],['Purpose',p.purpose],['Source',p.source],['Acquired',p.acquisitionDate],['Notes',p.notes]].filter(([,v])=>v).map(([l,v])=>`<dt>${l}</dt><dd>${esc(v)}</dd>`).join('')}</dl><h2>Recent records</h2><div class="card">${data.state.events.filter(e=>e.subjectId===p.id||e.destinationId===p.id).sort((a,b)=>b.occurredOn.localeCompare(a.occurredOn)||b.order-a.order).map(eventRow).join('')}</div><div class="danger-zone">${p.kind==='group'&&p.count?button('Identify one animal from this group','event-form','data-type="identify"'):''}${!p.active?button(p.archived?'Restore record':'Archive record',p.archived?'restore':'archive'):''}${button('Remove mistaken animal record','remove-profile','','quiet danger')}</div>`;}
function records(){return `<h1 tabindex="-1">Records</h1><p class="muted">What happened, when it happened, and what changed.</p><div class="grid"><div><label for="record-subject">Animal or group</label><select id="record-subject"><option value="">All animals</option>${currentProfiles().map(p=>`<option value="${p.id}" ${eventFilter===p.id?'selected':''}>${esc(title(p))}</option>`).join('')}</select></div><div><label for="record-date">From date</label><input type="date" id="record-date" value="${dateFilter}"></div></div><label for="record-type">Record type</label><select id="record-type">${options([['','All types'],...[['opening','Animals added'],['addition','Born or bought'],['departure','Left the farm'],['move','Moved'],['count','Count corrected'],['care','Care given'],['observation','Health observation'],['weight','Weight'],['note','Other note'],['identify','Identified'],['return','Returned']]],recordTypeFilter)}</select><div class="card" id="records-results">${recordResults()}</div><div class="actions">${button('+ Record something','record-choice','','primary')}</div>`;}
function recordResults(){return eventsForFarm().filter(e=>(!eventFilter||e.subjectId===eventFilter||e.destinationId===eventFilter)&&(!dateFilter||e.occurredOn>=dateFilter)&&(!recordTypeFilter||e.type===recordTypeFilter)).map(eventRow).join('')||'<p class="muted">No records match these filters.</p>';}
function eventDetail(){const e=data.state.events.find(e=>e.id===selected);return `${button('‹ Records','nav','data-screen="records"','quiet')}<h1 tabindex="-1">${esc(eventText(e))}</h1><p>${esc(title(subject(e.subjectId)))} · ${e.occurredOn}</p>${e.void?'<span class="badge">Removed from totals · history kept</span>':''}<div class="card"><p>${esc(e.notes||'No extra notes.')}</p>${e.reason?`<p><strong>Reason:</strong> ${esc(e.reason)}</p>`:''}${e.quantityText?`<p>${esc(e.quantityText)}</p>`:''}${e.affectedCount?`<p>Affected animals: ${e.affectedCount}</p>`:''}${e.basis?`<p>Weight basis: ${esc(e.basis.replaceAll('-',' '))}</p>`:''}${e.recordedAt?`<small>Recorded ${esc(new Date(e.recordedAt).toLocaleString())}</small>`:'<small>Saved on this device · pending sync</small>'}${e.photo?'<img id="event-photo" class="photo-preview" alt="Photo attached to record">':''}</div><div class="actions">${button(e.void?'Restore / correct record':'Correct record','correct-event')}${!e.void?button('Remove record','void-event','','danger'):''}</div>${e.revisions?.length?`<h2>Correction history</h2>${e.revisions.map(r=>`<div class="card"><p>${esc(r.reason)}</p><small>${esc(r.recordedAt||'Saved on this device')}</small><p>Previous: ${esc(eventText(r.before))} · ${esc(r.before.occurredOn)}</p></div>`).join('')}`:''}`;}
const input=(label,name,value='',type='text',extra='')=>`<label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${esc(value)}" ${extra}>`;
const options=(items,value)=>items.map(([v,l])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`).join('');
function locationField(value,farm=currentFarm()){return `<label for="locationId">Where are they kept?</label><select name="locationId" id="locationId">${options([['','Location not recorded'],...data.locations.filter(l=>l.data.farmId===farm).map(l=>[l.id,l.data.name])],value||'')}</select>${button('+ Add a location','add-location','','quiet')}`;}
function formShell(title,body,save='Save record'){return `${button('‹ Back','form-back','','quiet')}<h1 tabindex="-1">${title}</h1><form id="editor">${body}<p class="status" id="draft-status">Your draft is saved on this device as you type.</p><div id="preview"></div><div class="form-actions">${button('Cancel','form-back')}<button class="primary" type="submit">${save}</button></div></form>`;}
let formMode={},formValues={};
function animalForm(){const v=formValues,kind=formMode.kind,editing=formMode.edit;activePhoto=v.photo||'';return formShell(editing?'Edit details':kind==='group'?'Add a group':'Add one animal',`${!editing?`<label for="species">Animal type</label><select id="species" name="species">${options([...R.TYPES,...data.state.types.filter(t=>!t.retired)].map(t=>[t.id,t.name]),v.species||'cattle')}</select>`:''}${input(kind==='group'?'Group name':'Animal name (or enter a tag below)','name',v.name||'','text',kind==='group'?'required maxlength="160"':'maxlength="160"')}${kind==='individual'?input('Tag or other ID'+(v.name?' (optional)':''),'tag',v.tag||'','text','maxlength="160"'):!editing?input('Number of animals','quantity',v.quantity||'','number','required min="1" max="10000000" step="1" inputmode="numeric"'):''}${!editing?locationField(v.locationId):''}${!editing?input('Recorded on','occurredOn',v.occurredOn||today(),'date',`required max="${today()}"`):''}<details ${editing?'open':''}><summary>More details (optional)</summary><label for="breed" id="breed-label">${(v.species||'cattle')==='chicken'?'Breed or strain':'Breed'}</label><input id="breed" name="breed" list="breed-choices" value="${esc(v.breed||'')}" placeholder="Search, or enter a breed not listed" maxlength="160"><datalist id="breed-choices">${breedOptions(v.species||'cattle')}</datalist><small>Other / not listed? Enter the local name. You can save it in Animal options.</small>${kind==='individual'?`<label for="sex">Sex</label><select id="sex" name="sex">${options([['','Not recorded'],['female','Female'],['male','Male'],['unknown','Unknown']],v.sex||'')}</select><div class="grid"><div>${input('Birth date, if known','birthDate',v.birthDate||'','date',`max="${today()}"`)}</div><div>${input('Or estimated age','estimatedAge',v.estimatedAge||'','text','placeholder="e.g. About 2 years"')}</div></div>`:''}${input('Purpose','purpose',v.purpose||'')}${input('Source','source',v.source||'')}${input('Acquisition date','acquisitionDate',v.acquisitionDate||'','date',`max="${today()}"`)}${photoControl()}<label for="notes">Notes</label><textarea id="notes" name="notes" maxlength="4000">${esc(v.notes||'')}</textarea></details>`,editing?'Save details':kind==='group'?'Save group':'Save animal');}
function breedOptions(species){return [...(R.BREEDS[species]||[]),...data.state.breeds.filter(b=>b.species===species&&!b.retired).map(b=>b.name)].map(b=>`<option value="${esc(b)}">`).join('');}
function photoControl(){return `<div class="actions">${button(activePhoto?'Change photo':'Add photo','photo')}${activePhoto?button('Remove photo','remove-photo','','quiet'):''}</div>${activePhoto?'<p class="muted">Photo attached</p>':''}`;}
const eventNames={addition:'Born or added',move:'Moved',departure:'Left the farm',weight:'Weight',care:'Care or treatment given',observation:'Health observation',note:'Other note',count:'Correct a count',identify:'Identify one animal',return:'Animal returned'};
const commandNames={addition:'events.recordAddition',move:'events.recordMove',departure:'events.recordDeparture',weight:'events.recordWeight',care:'events.recordCare',observation:'events.recordObservation',note:'events.recordNote',count:'events.correctCount',identify:'animals.identifyFromGroup',return:'events.recordReturn'};
function eventForm(){const v=formValues,type=formMode.type,p=subject(formMode.subjectId);activePhoto=v.photo||'';let body=`<div class="card row">${symbol(p.species)}<div><strong>${esc(title(p))}</strong><small>${p.count} animals · ${esc(locName(p.locationId))}</small></div></div>${input('When did it happen?','occurredOn',v.occurredOn||today(),'date',`required max="${today()}"`)}`;
 if(['addition','departure','return'].includes(type)){const choices=type==='addition'?['Born / hatched','Bought','Added']:type==='departure'?['Sold','Transferred','Died','Lost','Other']:['Returned'];body+=`<label for="reason">What happened?</label><select name="reason" id="reason">${options(choices.map(x=>[x,x]),v.reason||choices[0])}</select>`;}
 if(['addition','departure','move','count'].includes(type)&&p.kind==='group')body+=input(type==='count'?'Correct number of animals':type==='move'?'How many moved?':'How many animals?','quantity',v.quantity??(type==='move'?p.count:''),'number',`required min="${type==='count'?0:1}" max="10000000" step="1" inputmode="numeric"`);
 if(['move','return','identify'].includes(type)){body+=locationField(v.locationId||p.locationId);if(type==='move'&&p.kind==='group')body+=`<label for="destinationId">Destination group</label><select name="destinationId" id="destinationId">${options([['','Move the whole group'],['new','Create a separate group'],...currentProfiles().filter(d=>d.id!==p.id&&d.kind==='group'&&d.species===p.species&&!d.archived&&(d.breed||'')===(p.breed||'')).map(d=>[d.id,title(d)+' · '+locName(d.locationId)])],v.destinationId||'')}</select>${input('New group name (when creating a group)','destinationName',v.destinationName||'')}`;if(type==='identify')body+=`${input('Animal name','destinationName',v.destinationName||'','text','required')}${input('Tag or other ID (optional)','destinationTag',v.destinationTag||'')}`;}
 if(type==='weight')body+=`${input('Weight','weight',v.weight||'','number','required min="0.001" step="any" inputmode="decimal"')}<div class="grid"><div><label for="unit">Unit</label><select name="unit" id="unit">${options(['kg','lb','g'].map(x=>[x,x]),v.unit||'kg')}</select></div><div><label for="basis">What was weighed?</label><select name="basis" id="basis">${options(p.kind==='group'?[['group-total','Whole group'],['group-average','Average per animal']]:[['individual','This animal']],v.basis|| (p.kind==='group'?'group-total':'individual'))}</select></div></div>`;
 if(type==='count')body+=input('Why is the count being corrected?','reason',v.reason||'','text','required');
 if(['care','observation'].includes(type)&&p.kind==='group')body+=input('Affected animals (optional)','affectedCount',v.affectedCount||'','number','min="1" step="1" inputmode="numeric"');
 if(type==='care')body+=input('Quantity and unit (optional)','quantityText',v.quantityText||'','text','placeholder="e.g. 5 kg of feed"');
 body+=`<label for="notes">${['care','observation','note'].includes(type)?'What happened?':'Notes (optional)'}</label><textarea id="notes" name="notes" maxlength="4000" ${['care','observation','note'].includes(type)?'required':''}>${esc(v.notes||'')}</textarea>${photoControl()}`;
 return formShell(eventNames[type],body,['move','count','departure','identify'].includes(type)?'Review change':'Save record');}
function correctionForm(){const e=data.state.events.find(e=>e.id===formMode.eventId),v=formValues;return formShell(e.void?'Restore / correct record':'Correct record',`<p>${esc(eventText(e))}</p>${input('Correct date','occurredOn',v.occurredOn||e.occurredOn,'date',`required max="${today()}"`)}${e.quantity!=null?input(e.type==='count'?'Correct count':'Correct number','quantity',v.quantity??e.quantity,'number',`required min="${e.type==='count'?0:1}" step="1"`):''}${e.type==='weight'?input('Correct weight','weight',v.weight??e.weight,'number','required min="0.001" step="any"'):''}${input('Reason for the original event','reason',v.reason??e.reason)}<label for="notes">Notes</label><textarea id="notes" name="notes">${esc(v.notes??e.notes)}</textarea>${input('Why are you correcting this record?','correctionReason',v.correctionReason||'','text','required')}`,'Review correction');}
function animalOptions(){return `<h1 tabindex="-1">Animal options</h1><p class="muted">Keep your local animal names easy to find.</p><div class="actions">${button('Add a breed','new-breed')}${button('Add an animal type','new-type')}</div><h2>Your breed names</h2>${data.state.breeds.filter(b=>!b.retired).map(b=>`<div class="option-row"><span>${esc(b.name)}<small>${esc(labelType(b.species))}</small></span>${button('Rename','rename-option',`data-kind="Breed" data-id="${b.id}"`)}${button('Retire','retire-option',`data-kind="Breed" data-id="${b.id}"`,'quiet')}</div>`).join('')||'<p class="muted">Standard breeds are ready to use. Add a local breed when you need it.</p>'}<h2>Animal types</h2><p>${R.TYPES.map(t=>t.name).join(' · ')}</p>${data.state.types.filter(t=>!t.retired).map(t=>`<div class="option-row"><span>${esc(t.name)}</span>${button('Rename','rename-option',`data-kind="Type" data-id="${t.id}"`)}${button('Retire','retire-option',`data-kind="Type" data-id="${t.id}"`,'quiet')}</div>`).join('')}<h2>Your data</h2><div class="actions">${button('Export records','export')}${button('Sync now','sync')}</div>${status()}${data.conflict?`<div class="error"><strong>These changes need review.</strong><p>${esc(data.conflict)}</p><p>Your local records and pending changes are still saved. Export them before choosing the server copy.</p><div class="actions">${button('Review pending changes','review-conflict')}${button('Use server copy','discard-conflict')}</div></div>`:''}`;}
function render(){const isForm=['animal-form','event-form','correction-form'].includes(screen);let body;if(!data.farms.length){body='<h1>My Animals</h1>'+empty('Choose a home for your animals','Add your farm once in FarmerPlus. Mapping can wait.','add-farm','Add a farm');}else body=isForm?(screen==='animal-form'?animalForm():screen==='event-form'?eventForm():correctionForm()):({overview,animals,detail,records,'event-detail':eventDetail,options:animalOptions}[screen]||overview)();app.innerHTML=`<main class="content">${!isForm&&data.farms.length?header():''}${body}${!isForm?status():''}</main>${!isForm?nav():''}`;app.removeAttribute('aria-busy');theme(data.theme);if(screen==='detail'&&subject(selected)?.photo)loadPhoto('detail-photo',subject(selected).photo);if(screen==='event-detail'){const e=data.state.events.find(e=>e.id===selected);if(e?.photo)loadPhoto('event-photo',e.photo);}bind();}
async function loadPhoto(id,hash){try{const src=await api('media.getPreview',{hash});const img=document.getElementById(id);if(img)img.src=src;}catch{const img=document.getElementById(id);if(img)img.replaceWith(document.createTextNode('Photo will be available after download.'));}}
function formData(){return Object.fromEntries(new FormData(document.getElementById('editor')).entries());}
async function saveDraft(){if(!document.getElementById('editor'))return;const draft={screen,mode:formMode,values:{...formData(),photo:activePhoto},farmId:currentFarm()};await api('drafts.put',{key:'form',data:draft});data.draft=draft;const status=document.getElementById('draft-status');if(status)status.textContent='Draft saved on this device';}
function scheduleDraft(){clearTimeout(draftTimer);draftTimer=setTimeout(()=>saveDraft().catch(e=>error('Draft could not be saved: '+e.message)),250);pendingPreview=null;const preview=document.getElementById('preview');if(preview)preview.replaceChildren();}
function startAnimal(kind,edit){formBack=edit?'detail':'animals';formMode={kind,edit:edit?.id||null,id:edit?.id||uuid(),eventId:uuid()};formValues=edit?{...edit}:{species:'cattle',occurredOn:today()};setScreen('animal-form');}
function startEvent(type){const p=subject(selected);if(!p)throw Error('Choose an animal first.');formMode={type,subjectId:p.id,eventId:uuid(),destinationId:uuid()};formValues={occurredOn:today()};formBack='detail';setScreen('event-form');}
function makeCommand(v){let name,payload;if(screen==='animal-form'){payload={...v,photo:activePhoto,id:formMode.id};if(formMode.edit){name='animals.updateProfile';}else{name=formMode.kind==='group'?'animals.createGroup':'animals.createIndividual';Object.assign(payload,{farmId:currentFarm(),eventId:formMode.eventId,quantity:formMode.kind==='group'?Number(v.quantity):1});}}
 else if(screen==='correction-form'){name='events.correct';const replacement={occurredOn:v.occurredOn,notes:v.notes,reason:v.reason};if(v.quantity!==undefined)replacement.quantity=Number(v.quantity);if(v.weight!==undefined)replacement.weight=Number(v.weight);payload={id:formMode.eventId,correctionReason:v.correctionReason,replacement};}
 else {name=commandNames[formMode.type];payload={...v,subjectId:formMode.subjectId,eventId:formMode.eventId,farmId:currentFarm(),quantity:formMode.type==='identify'?1:v.quantity?Number(v.quantity):1,photo:activePhoto};if(v.weight)payload.weight=Number(v.weight);if(v.affectedCount)payload.affectedCount=Number(v.affectedCount);else delete payload.affectedCount;if(v.destinationId==='new'||formMode.type==='identify'){payload.destinationId=formMode.destinationId;payload.newDestination={name:v.destinationName,tag:v.destinationTag||''};}delete payload.destinationName;delete payload.destinationTag;}
 return {operationId:uuid(),deviceId:data.deviceId,schemaVersion:1,ruleVersion:1,expectedRevision:data.revision,name,payload};}
async function commit(command,projection){if(saveBusy)return;saveBusy=true;document.querySelectorAll('#editor button').forEach(b=>b.disabled=true);try{data=await api('commands.enqueue',{command,state:projection});await api('drafts.remove',{key:'form'});data.draft=null;selected=command.payload.id||command.payload.subjectId;screen=command.name.startsWith('options.')?'options':'detail';if(command.name==='events.correct'||command.name==='events.void'){selected=command.payload.id;screen='event-detail';}if(command.name==='animals.removeMistakenProfile')screen='animals';render();notice('Saved on this device');}finally{saveBusy=false;document.querySelectorAll('#editor button').forEach(b=>b.disabled=false);}}
function previewHtml(next){const changed=next.profiles.filter(p=>{const old=data.state.profiles.find(o=>o.id===p.id);return !old||old.count!==p.count||old.locationId!==p.locationId||old.active!==p.active;});const before=data.state.profiles.filter(p=>p.farmId===currentFarm()&&!p.deleted).reduce((n,p)=>n+p.count,0),after=next.profiles.filter(p=>p.farmId===currentFarm()&&!p.deleted).reduce((n,p)=>n+p.count,0);return `<div class="review"><h3>After this change</h3>${changed.map(p=>{const old=data.state.profiles.find(o=>o.id===p.id);return `<div class="row"><span>${esc(title(p))}<small>${esc(locName(p.locationId))}</small></span><strong>${old?.count||0} → ${p.count}</strong></div>`;}).join('')||'<p>Details will be corrected. Animal numbers stay the same.</p>'}<hr class="subtle-rule"><div class="row"><span>Total on this farm</span><strong>${before} → ${after}</strong></div><p class="muted">The history is kept. Counts are checked again when syncing.</p>${button('Confirm and save','confirm-preview','','primary')}</div>`;}
async function submit(e){e.preventDefault();if(saveBusy)return;await saveDraft();const command=makeCommand(formData()),projection=R.apply(data.state,command,ctx(),today());if(screen==='correction-form'||(screen==='event-form'&&['move','departure','count','identify'].includes(formMode.type))){pendingPreview={command,projection};document.getElementById('preview').innerHTML=previewHtml(projection);document.getElementById('preview').scrollIntoView({block:'nearest'});}else await commit(command,projection);}
async function dialog(title,body,submitText='Continue'){return new Promise(resolve=>{const d=document.createElement('dialog');d.innerHTML=`<form method="dialog"><h2 style="margin-top:0">${esc(title)}</h2>${body}<div class="actions"><button type="button" data-cancel>Cancel</button><button class="primary" type="submit">${esc(submitText)}</button></div></form>`;document.body.append(d);d.querySelector('[data-cancel]').onclick=()=>d.close();d.addEventListener('close',()=>{resolve(null);d.remove();},{once:true});d.querySelector('form').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));resolve(v);d.close();};d.showModal();});}
async function commandNow(name,payload,review=false){const c={operationId:uuid(),deviceId:data.deviceId,schemaVersion:1,ruleVersion:1,expectedRevision:data.revision,name,payload},s=R.apply(data.state,c,ctx(),today());if(review&&!await dialog('Review change',previewHtml(s).replace(/<button[\s\S]*?<\/button>/,''),'Save change'))return;await commit(c,s);}
async function action(control){const a=control.dataset.action,id=control.dataset.id;switch(a){case 'nav':if(control.dataset.screen==='animals'||!control.dataset.screen)selected=null;setScreen(control.dataset.screen||'animals');break;case 'detail':selected=id;setScreen('detail');break;case 'event-detail':selected=id;setScreen('event-detail');break;case 'species':speciesFilter=id;filter='all';setScreen('animals');break;case 'filter':filter=id;render();break;case 'clear-filters':filter='all';speciesFilter=query=locationFilter=breedFilter='';showArchived=false;render();break;
 case 'filters':{const v=await dialog('Filter animals',`<label>Animal type<select name="species">${options([['','All types'],...[...R.TYPES,...data.state.types].map(t=>[t.id,t.name])],speciesFilter)}</select></label><label>Location<select name="location">${options([['','All locations'],['unknown','Not recorded'],...data.locations.filter(l=>l.data.farmId===currentFarm()).map(l=>[l.id,l.data.name])],locationFilter)}</select></label>${input('Breed contains','breed',breedFilter)}<label>Show<select name="state">${options([['active','Active animals'],['inactive','Inactive / archived animals']],showArchived?'inactive':'active')}</select></label>`,'Apply filters');if(v){speciesFilter=v.species;locationFilter=v.location;breedFilter=v.breed;showArchived=v.state==='inactive';render();}break;}
 case 'add-choice':{const v=await dialog('What would you like to add?',`<label for="kind">Choose one</label><select name="kind" id="kind"><option value="individual">One animal · a name or tag</option><option value="group">A group · a flock or herd</option></select>`);if(v)startAnimal(v.kind);break;}
 case 'edit':startAnimal(subject(id).kind,subject(id));break;
 case 'record-choice':{if(id)selected=id;if(!subject(selected)){const v=await dialog('Choose animals',`<label>Animal or group<select name="id">${options(currentProfiles().filter(p=>!p.archived).map(p=>[p.id,title(p)]),'')}</select></label>`);if(!v)return;selected=v.id;}const p=subject(selected);if(!p)throw Error('Add animals before recording an event.');const choices=Object.entries(eventNames).filter(([k])=>k!=='identify'&&(p.kind==='group'||!['addition','count'].includes(k))&&(p.active?k!=='return':['return','count','addition'].includes(k)));const d=document.createElement('dialog');d.innerHTML=`<h2>What happened?</h2><p>${esc(title(p))}</p><div class="choices">${choices.map(([type,label])=>button(esc(label),'event-form',`data-type="${type}"`,'choice')).join('')}</div>${button('Cancel','close-dialog','','quiet')}`;d.onclick=e=>{const b=e.target.closest('button');if(!b)return;d.close();d.remove();if(b.dataset.type)startEvent(b.dataset.type);};d.oncancel=()=>d.remove();document.body.append(d);d.showModal();break;}
 case 'event-form':startEvent(control.dataset.type);break;
 case 'form-back':await saveDraft();setScreen(formBack);break;
 case 'photo':await saveDraft();{const photo=await api('media.choosePhoto');if(photo){activePhoto=photo.hash;formValues={...formData(),photo:activePhoto};render();await saveDraft();}}break;
 case 'remove-photo':formValues={...formData(),photo:''};activePhoto='';render();await saveDraft();break;
 case 'add-farm':await api('farms.create');data=await api('context.get');render();break;
 case 'add-location':await saveDraft();await api('locations.create',{farmId:currentFarm()});formValues={...formData(),photo:activePhoto};data=await api('context.get');render();break;
 case 'resume-draft':{const d=data.draft;if(!data.farms.some(f=>f.id===d.farmId))throw Error('The draft’s farm is no longer available. Export your data before discarding it.');data.farmId=d.farmId;formMode=d.mode;formValues=d.values;formBack='overview';setScreen(d.screen);break;}
 case 'discard-draft':if(await dialog('Discard this draft?','<p>The saved animal records will be kept.</p>','Discard draft')){await api('drafts.remove',{key:'form'});data.draft=null;render();}break;
 case 'confirm-preview':if(pendingPreview)await commit(pendingPreview.command,pendingPreview.projection);break;
 case 'correct-event':formMode={eventId:selected};formValues={};formBack='event-detail';setScreen('correction-form');break;
 case 'void-event':{const v=await dialog('Remove this record?',`<p>This removes its effect on counts and locations. The original history is kept.</p>${input('Why are you removing it?','reason','','text','required')}`,'Review removal');if(v)await commandNow('events.void',{id:selected,correctionReason:v.reason},true);break;}
 case 'archive':case 'restore':await commandNow('animals.'+a,{id:selected});break;
 case 'remove-profile':{const v=await dialog('Remove a mistaken animal record?',`<p>Use this only for a record created in error. For sold, lost or dead animals, record that they left the farm.</p>${input('Reason','reason','','text','required')}`,'Review removal');if(v)await commandNow('animals.removeMistakenProfile',{id:selected,reason:v.reason},true);break;}
 case 'options':setScreen('options');break;
 case 'new-breed':case 'new-type':{const breed=a==='new-breed',v=await dialog(breed?'Add a breed':'Add an animal type',`${breed?`<label>Animal type<select name="species">${options([...R.TYPES,...data.state.types.filter(t=>!t.retired)].map(t=>[t.id,t.name]),'cattle')}</select></label>`:''}${input('Name','name','','text','required maxlength="160"')}`,'Save option');if(v)await commandNow('options.create'+(breed?'Breed':'Type'),{id:uuid(),...v});break;}
 case 'rename-option':case 'retire-option':{const kind=control.dataset.kind,row=data.state[kind==='Breed'?'breeds':'types'].find(r=>r.id===id),rename=a==='rename-option',v=await dialog(rename?'Rename custom option':'Retire custom option',rename?input('Name','name',row.name,'text','required'):'<p>Existing records keep this name. It will be hidden from new selections.</p>',rename?'Save name':'Retire');if(v)await commandNow('options.'+(rename?'rename':'retire')+kind,{id,...v});break;}
 case 'sync':await api('sync.request');data=await api('context.get');render();notice(data.status);break;
 case 'export':await api('exports.create');notice('Animal records and pending changes exported');break;
 case 'discard-conflict':if(await dialog('Use the server copy?','<p>Export your local records first. This discards all pending animal commands on this device, and keeps an internal recovery copy.</p>','Use server copy')){data=await api('conflicts.discard');render();}break;
 case 'review-conflict':{const remote=await api('conflicts.remote');let s=remote.state,revision=remote.revision;const queue=[];for(const item of data.queue){const c={...item,operationId:uuid(),expectedRevision:revision++};s=R.apply(s,c,ctx(),today());queue.push(c);}const v=await dialog('Reapply pending changes?',`<p>${queue.length} changes can be applied to the current server copy. Review the resulting totals.</p>${previewHtml(s).replace(/<button[\s\S]*?<\/button>/,'')}`,'Save revised changes');if(v){data=await api('conflicts.rebase',{state:s,queue,serverRevision:remote.revision});render();notice('Changes revised and queued for sync');}break;}
 }}
function bind(){app.onclick=e=>{const b=e.target.closest('button[data-action]');if(b)action(b).catch(e=>error(e.message));};const f=document.getElementById('editor');if(f){f.onsubmit=e=>submit(e).catch(e=>error(e.message));f.oninput=scheduleDraft;f.onchange=scheduleDraft;}document.getElementById('farm')?.addEventListener('change',async e=>{try{data.farmId=e.target.value;await api('context.selectFarm',{farmId:data.farmId});selected=null;setScreen('overview');}catch(e){error(e.message);}});document.getElementById('search')?.addEventListener('input',e=>{query=e.target.value;document.getElementById('animal-results').innerHTML=animalResults();});document.getElementById('record-subject')?.addEventListener('change',e=>{eventFilter=e.target.value;document.getElementById('records-results').innerHTML=recordResults();});document.getElementById('record-type')?.addEventListener('change',e=>{recordTypeFilter=e.target.value;document.getElementById('records-results').innerHTML=recordResults();});document.getElementById('record-date')?.addEventListener('change',e=>{dateFilter=e.target.value;document.getElementById('records-results').innerHTML=recordResults();});document.getElementById('species')?.addEventListener('change',e=>{document.getElementById('breed-label').textContent=e.target.value==='chicken'?'Breed or strain':'Breed';document.getElementById('breed-choices').innerHTML=breedOptions(e.target.value);document.getElementById('breed').value='';});}
try{data=await api('context.get');render();FarmerPlus.onUpdate(async()=>{if(saveBusy)return;const next=await api('context.get');if(document.getElementById('editor')){data.queue=next.queue;data.status=next.status;data.conflict=next.conflict;theme(next.theme);}else{data=next;render();}});}catch(e){app.innerHTML=`<main class="content"><h1>My Animals could not open</h1><p class="error">${esc(e.message)}</p><p>Return to FarmerPlus and try again. Your saved records are kept.</p></main>`;}
})();
