/* Pure local projection rules. Server independently validates every command. */
(function(root){
'use strict';
const BREEDS={cattle:['Angus','Hereford','Charolais','Holstein-Friesian','Jersey','Brown Swiss','Brahman','Simmental','Limousin','Nelore'],pigs:['Large White (Yorkshire)','Landrace','Duroc','Pietrain','Hampshire','Berkshire'],chicken:['Cornish Cross','Ross 308','Cobb 500','Leghorn','Rhode Island Red','Plymouth Rock','Hubbard','Arbor Acres','Lohmann Brown','Hy-Line Brown'],goats:['Saanen','Anglo-Nubian (Nubian)','Boer','Toggenburg','Alpine','West African Dwarf','Angora','Creole'],sheep:['Merino','Suffolk','Dorper','Awassi','Texel','Dorset','Rambouillet','East Friesian','Lacaune','Karakul']};
const TYPES=Object.keys(BREEDS).map((id,i)=>({id,name:['Cattle','Pigs','Chicken','Goats','Sheep'][i]}));
const FIELDS=['name','tag','breed','sex','birthDate','estimatedAge','purpose','source','acquisitionDate','notes','photo'];
const clone=x=>JSON.parse(JSON.stringify(x));
function check(ok,msg){if(!ok)throw Error(msg);}
function uid(x){check(typeof x==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/.test(x),'Use a valid record identifier.');return x;}
function text(x,label='Text',limit=160,required=false){check(typeof x==='string',label+' must be text.');x=x.trim();check(x.length<=limit&&(!required||x.length>0),'Check '+label.toLowerCase()+' (maximum '+limit+' characters).');return x;}
function day(x,today){check(typeof x==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(x)&&Number.isFinite(Date.parse(x))&&new Date(x).toISOString().slice(0,10)===x&&x<=today,'Choose today or an earlier valid date.');return x;}
function count(x,min=0){check(Number.isSafeInteger(x)&&x>=min&&x<=10000000,'Enter a whole number of animals within the allowed range.');return x;}
function empty(){return {profiles:[],events:[],types:[],breeds:[]};}
function profile(s,id){const p=s.profiles.find(p=>p.id===id&&!p.deleted);check(p,'This animal or group is no longer available.');return p;}
function location(farmId,locationId,ctx){uid(farmId);check(Object.hasOwn(ctx.farms,farmId),'Choose one of your saved farms.');if(locationId){uid(locationId);check(ctx.locations[locationId]===farmId,'Choose a location on this farm.');}return locationId||null;}
function values(v,today){const r={};for(const k of FIELDS)if(Object.hasOwn(v,k))r[k]=text(v[k]||'',k,k==='notes'?4000:160);check(['','female','male','unknown'].includes(r.sex||''),'Choose a valid sex.');check(!(r.birthDate&&r.estimatedAge),'Enter a birth date or an estimated age, not both.');for(const k of ['birthDate','acquisitionDate'])if(r[k])day(r[k],today);check(!r.photo||/^[a-f0-9]{64}$/.test(r.photo),'Choose a valid photo.');return r;}
function newProfile(s,v,kind,ctx,today){uid(v.id);check(!s.profiles.some(p=>p.id===v.id),'This animal record already exists.');check(Object.hasOwn(BREEDS,v.species)||s.types.some(t=>t.id===v.species&&!t.retired),'Choose an animal type.');const fields=values(v,today);check(fields.name||(kind==='individual'&&fields.tag),'Enter a name or tag.');const p={id:v.id,kind,species:v.species,initialFarmId:v.farmId,initialLocationId:location(v.farmId,v.locationId,ctx),...fields};s.profiles.push(p);return p;}
function eventValues(v,type,s,ctx,today){const p=profile(s,v.subjectId),e={id:uid(v.eventId),type,subjectId:p.id,occurredOn:day(v.occurredOn,today),notes:text(v.notes||'','Notes',4000),reason:text(v.reason||'','Reason'),photo:text(v.photo||'','Photo',64)};check(!e.photo||/^[a-f0-9]{64}$/.test(e.photo),'Choose a valid photo.');
 if(['addition','departure','return','move','count','opening','identify'].includes(type))e.quantity=count(v.quantity??1,type==='count'?0:1);
 if(['count','departure','addition','return'].includes(type))check(e.reason,'Explain what happened.');
 if(['care','observation','note'].includes(type)){check(e.notes,'Describe what happened.');if(v.affectedCount!=null)e.affectedCount=count(v.affectedCount,1);e.quantityText=text(v.quantityText||'','Quantity and unit');}
 if(type==='weight'){check(typeof v.weight==='number'&&Number.isFinite(v.weight)&&v.weight>0&&v.weight<=100000000,'Enter a positive weight.');check(['kg','lb','g'].includes(v.unit),'Choose a weight unit.');check(['individual','group-total','group-average'].includes(v.basis),'Choose what this weight measures.');check((p.kind==='individual')===(v.basis==='individual'),'The weight basis must match this animal or group.');Object.assign(e,{weight:v.weight,unit:v.unit,basis:v.basis});}
 if(['opening','move','return','identify'].includes(type)){e.farmId=v.farmId||p.farmId||p.initialFarmId;e.locationId=location(e.farmId,v.locationId,ctx);}
 if(['move','identify'].includes(type)){e.destinationId=v.destinationId||null;if(e.destinationId)uid(e.destinationId);}return e;}
function project(s){const byId=Object.fromEntries(s.profiles.map(p=>[p.id,p]));for(const p of s.profiles)Object.assign(p,{count:0,farmId:p.initialFarmId,locationId:p.initialLocationId,active:false,lastDeparture:''});
 for(const e of [...s.events].sort((a,b)=>a.occurredOn.localeCompare(b.occurredOn)||a.order-b.order||a.id.localeCompare(b.id))){if(e.void)continue;const p=byId[e.subjectId],n=e.quantity||0;check(p&&!p.deleted,'A later record still depends on this animal. Correct it first.');
 switch(e.type){case 'opening':check(p.count===0,'An opening balance already exists.');Object.assign(p,{count:n,farmId:e.farmId,locationId:e.locationId});break;
 case 'addition':check(p.kind==='group','Additions belong to a group.');p.count+=n;break;
 case 'count':check(p.kind==='group','Count corrections belong to a group.');p.count=n;break;
 case 'departure':check(p.count>=n,'There are not enough animals on this date. Check later dependent records too.');p.count-=n;p.lastDeparture=e.reason;break;
 case 'return':check(p.kind==='individual'&&p.count===0&&p.lastDeparture&&p.lastDeparture.toLowerCase()!=='died','Correct the departure before returning this animal.');Object.assign(p,{count:1,farmId:e.farmId,locationId:e.locationId,lastDeparture:''});break;
 case 'move':case 'identify':check(p.count>=n,'There are not enough animals to move on this date.');if(e.destinationId){const d=byId[e.destinationId];check(d&&!d.deleted&&d.id!==p.id,'Choose a different destination group.');check(p.kind==='group'&&d.species===p.species,'Only matching animals can be transferred together.');check((d.breed||'')===(p.breed||''),'Choose a group with the same breed, or create a new group.');check((e.type==='identify'&&d.kind==='individual'&&n===1&&d.count===0)||(e.type==='move'&&d.kind==='group'),'Check the destination animal type.');check(d.count===0||(d.farmId===e.farmId&&d.locationId===e.locationId),'The destination group is at another location.');p.count-=n;Object.assign(d,{count:d.count+n,farmId:e.farmId,locationId:e.locationId});check(d.count<=10000000,"This history would create an invalid animal count.");}else{check(e.type==='move'&&n===p.count,'A partial move needs a destination group.');Object.assign(p,{farmId:e.farmId,locationId:e.locationId});}break;
 default:check(p.count>0,'This animal was not present on the record date.');check((e.affectedCount||1)<=p.count,'The affected number exceeds the animals present on this date.');}
 check(p.count>=0&&p.count<=10000000&&(p.kind==='group'||p.count<=1),'This history would create an invalid animal count.');}
 const tags=new Set();for(const p of s.profiles){p.active=p.count>0&&!p.archived&&!p.deleted;if(p.tag&&!p.deleted){const key=p.farmId+':'+p.tag.trim().toLowerCase();check(!tags.has(key),'This tag is already recorded on the farm.');tags.add(key);}check(!p.archived||p.count===0,'An archived animal has later active records. Restore it first.');}return s;}
function apply(state,command,ctx,today=new Date().toISOString().slice(0,10)){const s=clone(state),v=command.payload||{},name=command.name;
 if(['animals.createIndividual','animals.createGroup'].includes(name)){const kind=name.endsWith('Group')?'group':'individual',p=newProfile(s,v,kind,ctx,today),e=eventValues({...v,subjectId:p.id,quantity:kind==='group'?v.quantity:1},'opening',s,ctx,today);check(!s.events.some(x=>x.id===e.id),'This record identifier is already used.');s.events.push({...e,order:s.events.length,revisions:[]});}
 else if(name==='animals.updateProfile'){const p=profile(s,v.id);check(!['farmId','locationId','count','quantity','species','kind'].some(k=>Object.hasOwn(v,k)),'Use a movement or count record for this change.');Object.assign(p,values({...p,...v},today));check(p.name||(p.kind==='individual'&&p.tag),'Enter a name or tag.');}
 else if(['animals.archive','animals.restore','animals.removeMistakenProfile'].includes(name)){const p=profile(s,v.id);if(name==='animals.restore')p.archived=false;else if(name==='animals.archive'){check(p.count===0,'Record animals leaving before archiving this record.');p.archived=true;}else{const reason=text(v.reason||'','Reason',160,true),linked=s.events.filter(e=>!e.void&&(e.subjectId===p.id||e.destinationId===p.id));check(linked.every(e=>e.type==='opening'),'Correct or remove later dependent records first.');for(const e of linked){const {revisions,...before}=e;e.revisions.push({before:clone(before),reason});e.void=true;}p.deleted=true;}}
 else if(['events.correct','events.void'].includes(name)){const e=s.events.find(e=>e.id===v.id);check(e,'The record no longer exists.');const reason=text(v.correctionReason||'','Correction reason',160,true),{revisions,...before}=clone(e);if(name==='events.void')e.void=true;else{const r=v.replacement||{};check(!['id','type','subjectId','destinationId','farmId'].some(k=>Object.hasOwn(r,k)),'A correction cannot change the animals involved. Void the record and create a new one.');Object.assign(e,eventValues({...e,...r,eventId:e.id},e.type,s,ctx,today),{void:false});}e.revisions.push({before,reason});}
 else if(name?.startsWith('events.record')||name==='events.correctCount'||name==='animals.identifyFromGroup'){const map={'events.recordAddition':'addition','events.recordDeparture':'departure','events.recordReturn':'return','events.recordMove':'move','events.recordWeight':'weight','events.recordCare':'care','events.recordObservation':'observation','events.recordNote':'note','events.correctCount':'count','animals.identifyFromGroup':'identify'},kind=map[name];check(kind,'Unsupported record action.');if(v.newDestination){const p=profile(s,v.subjectId);newProfile(s,{...v.newDestination,id:v.destinationId,species:p.species,breed:p.breed||'',farmId:v.farmId||p.farmId,locationId:v.locationId},kind==='identify'?'individual':'group',ctx,today);}const e=eventValues(v,kind,s,ctx,today);check(!s.events.some(x=>x.id===e.id),'This record identifier is already used.');s.events.push({...e,order:s.events.length,revisions:[]});}
 else if(name?.startsWith('options.')){const m=/^options\.(create|rename|retire)(Breed|Type)$/.exec(name);check(m,'Unsupported animal option.');const [,action,kind]=m,rows=s[kind==='Breed'?'breeds':'types'],id=uid(v.id);let row=rows.find(r=>r.id===id);if(action==='create'){check(!row,'This option already exists.');row={id};if(kind==='Breed'){check(Object.hasOwn(BREEDS,v.species)||s.types.some(t=>t.id===v.species&&!t.retired),'Choose an animal type.');row.species=v.species;}rows.push(row);}check(row,'Standard choices cannot be changed; choose a custom option.');if(action==='retire')row.retired=true;else{const label=text(v.name,'Name',160,true);check(!rows.some(r=>r.id!==id&&r.name?.toLowerCase()===label.toLowerCase()&&r.species===row.species),'That option already exists.');row.name=label;}}
 else throw Error('Unsupported animal action.');
 check(s.profiles.length<=10000&&s.events.length<=50000,'This app has reached its record limit. Export and contact your administrator.');return project(s);}
const api={apply,project,empty,BREEDS,TYPES};if(typeof module!=='undefined')module.exports=api;else root.AnimalRules=api;
})(globalThis);
